{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gin-next-2022-06-11t11-36-32-frontend.serviceAccountName" . }}
  labels:
    {{- include "gin-next-2022-06-11t11-36-32-frontend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
